name: firstworkflow
on: push
jobs:
  learn-actions:
    runs-on: ubuntu-20.04

    steps:
      - name: echo-string
        run: echo "Hello world Example"
      - name: Multiple-command
        run: | 
         node -v
         npm -vs  
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: Get SW version
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: parallel-job
    steps:
      - name: echo a string
        run: Write-Output "windows string"



