name: continue-on-error
on:
    workflow_dispatch: 
        inputs:
            pass-input-tests:
                type: boolean
                default: false
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build the app
              run: echo "building applictaion"
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Running test 
              run: |
                echo "Running tests...."
            - name: fail the test
              if: ${{!inputs.pass-input-tests}}
            #  continue-on-error: true
              run: exit 1    
                                          