name: Repo-events
on: 
    push:
    pull_request:
        types: [opened,assigned,closed]
jobs:
    check-repo-events:
        runs-on: ubuntu-latest
        steps:
            - run: |
               echo $GITHUB_SHA
               echo $GITHUB_REF
            - uses: actions/checkout@v4   