name: Repo-events
on: [push]
jobs:
    check-repo-events:
        runs-on: ubuntu-latest
        steps:
            - run: |
               echo $GITHUB_SHA
               echo $GITHUB_REF
            - uses: actions/checkout@v4   