name: Repo-events
on: 
    push:
        branches: 
            - main
jobs:
    check-repo-events:
        runs-on: ubuntu-latest
        steps:
            - run: |
               ech $GITHUB_SHA
               echo $GITHUB_REF
            - uses: actions/checkout@v4   