name: matirx-lab-include-1
on: [push]
jobs:
  node-matrix:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        node: [14]
        include:
          - os: windows-latest
            node: 16
            custom-value: value
      max-parallel: 2  
    runs-on: ${{matrix.os}}
    steps:
      - run: node -v
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: node -v         