name: manual-workflow
on:
    workflow_dispatch: 
        inputs:
            string: # name of the input
                description: A input String
                type: string
                required: true
                default: "Default Value"
            number:
                description: A number input
                default: 4
                type: number
            options:
                description: "give an option input"
                default: "Option 3"
                required: true
                type: choice
                options:
                    - Option 1
                    - Option 2
                    - Option 3  
            boolean:
                description: A bool option
                type: boolean
                default: true
                required: false
            environment:
                description: "Environment"
                type: environment
                required: true                  
jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF    
            - name: getting-input-values
              run: |
                echo "String: ${{inputs.string}}" 
                echo "Number: ${{inputs.number}}"
                echo "Option: ${{inputs.options}}"
                echo "Boolean: ${{inputs.boolean}}"
                echo "Environment: ${{inputs.environment}}"       
