name: status check function
on: [push]
run-name: "The workflow is pushed by ${{github.actor}} on branch ${{github.ref}}"
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: sleep 20
      - name: Runs on failure
        if: failure()
        run: echo 'Run only if failures'
      - name: Runs on success
        if: success()
        run: echo 'Run on success'
      - name: Always run
        if: always()
        run: echo 'Always run the step'
      - name: Runs when cancelled
        if: cancelled()
        run: echo 'Runs on cancelled'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'job-2'               